name: Deploy satic web site
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositery
        uses: action/checkout@v4

      - uses: setup pages
        uses: action/configure-pages@v4

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
